import HeaderMobile from "@/components/layout/HeaderMobile";
import "./globals.css";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="font-objectSans" lang="en">
      <body>
        <HeaderMobile />
        {children}
        <Footer />
      </body>
    </html>
  );
}
